/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cvs_com_ziparchiver_minizip_MiniZipWrapper */

#ifndef _Included_cvs_com_ziparchiver_minizip_MiniZipWrapper
#define _Included_cvs_com_ziparchiver_minizip_MiniZipWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cvs_com_ziparchiver_minizip_MiniZipWrapper
 * Method:    createZipFromFolder
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cvs_com_ziparchiver_minizip_MiniZipWrapper_createZipFromFolder
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     cvs_com_ziparchiver_minizip_MiniZipWrapper
 * Method:    createZipFromFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cvs_com_ziparchiver_minizip_MiniZipWrapper_createZipFromFile
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     cvs_com_ziparchiver_minizip_MiniZipWrapper
 * Method:    extractZip
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cvs_com_ziparchiver_minizip_MiniZipWrapper_extractZip
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     cvs_com_ziparchiver_minizip_MiniZipWrapper
 * Method:    getFilenameInZip
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cvs_com_ziparchiver_minizip_MiniZipWrapper_getFilenameInZip
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
